Repository eduNEXT/eox-core, pull requests merged in 2024-05, with the labels that each got.

#259 feat: added logs to errors imports
  eox_core/middleware.py
  eox_core/settings/production.py
Labels: waiting on author

#265 feat: add user lang cookie preference
  eox_core/edxapp_wrapper/backends/lang_pref_middleware_p_v1.py
  eox_core/edxapp_wrapper/backends/lang_pref_middleware_p_v1_test.py
  eox_core/edxapp_wrapper/language_preference.py
  eox_core/middleware.py
  eox_core/settings/common.py
  eox_core/settings/production.py
  eox_core/settings/test.py
  eox_core/tests/test_middleware.py
Labels: size/m

#267 feat: add integration test file
  eox_core/settings/test.py
  eox_core/tests/tutor/__init__.py
  eox_core/tests/tutor/conftest.py
  eox_core/tests/tutor/integration_test_tutor.py
  eox_core/tests/tutor/pytest.ini
  requirements/test.in
  requirements/test.txt
Labels: size/s
