Repository eduNEXT/eox-core, pull requests merged in 2024-10, with the labels that each got.

#280 feat: add integration tests for the enrollments api `AP-1346`
  .github/workflows/integration-test.yml
  Makefile
  eox_core/api/v1/tests/integration/data/fake_users.py
  eox_core/api/v1/tests/integration/test_views.py
  eox_core/settings/test.py
  fixtures/initial_data.json
Labels: size/l

#288 refactor(ci): update workflow for integration tests
  .github/workflows/integration-test.yml
Labels: size/xs

#292 chore: drop support for Python 3.10 and Django 3.2
  .github/workflows/tests.yml
  CHANGELOG.md
  README.rst
  eox_core/__init__.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/django32.txt
  requirements/pip-tools.txt
  requirements/test.txt
  requirements/tox.txt
  setup.cfg
  setup.py
  tox.ini
Labels: size/m

#293 ci: add dependabot config for enable github action auto update`AP-1514`
  .github/dependabot.yml
Labels: size/xs

#290 docs: add users api docs
  docs/how_to/users_api.rst
Labels: size/m
